w0 = window0()
w1 = window1()
w2 = window2()
action1.triggered.connect(w1.simcle)
action2.triggered.connect(w1.activate)
action3.triggered.connect(w0.activate)
action4.triggered.connect(w1.linebreak)
action5.triggered.connect(w2.activate)
button_action.triggered.connect(w1.simcle)
button_action2.triggered.connect(w1.linebreak)
app.setStyleSheet(style_sheet)
app.exec()
